# Data Analysis using NumPy and Pandas

In [6]:
import numpy as np

Step wise Instructions:

1. Create a 1D NumPy Array:

Create a 1D NumPy array named temperatures_w1 for Week 1 with the following values:

[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9]

In [7]:
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])
temperatures_w1

array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

_______________

2. Inspection and Properties:

● Inspect the shape, data type, and the number of elements in the array.

Inspect the shape of the temperatures_w1 array.

In [10]:
temperatures_w1.shape

(7,)

In [11]:
temperatures_w1.dtype

dtype('float64')

In [12]:
temperatures_w1.ndim

1

In [13]:
temperatures_w1.size

7

____________

3. Array Operations:

● Convert the temperatures_w1 from Celsius to Fahrenheit using the formula: Fahrenheit = (Celsius * 9/5) + 32

● Find the maximum, minimum, and mean temperatures for the week.

In [16]:
temperatures_w1

array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

In [ ]:
Fahrenheit = (Celsius * 9/5) + 32

In [14]:
Fahrenheit = (temperatures_w1 * 1.8) + 32

In [15]:
Fahrenheit

array([72.5 , 77.54, 69.44, 74.12, 78.98, 76.64, 71.42])

In [17]:
Fahrenheit.max()

78.98

In [18]:
Fahrenheit.min()

69.44

In [19]:
Fahrenheit.mean()

74.37714285714286

________________

In [ ]:
4. Array Slicing and Indexing:
● Extract the temperatures for the first three days of the week.
● Extract the temperatures for the weekend (last two days).
● Extract the temperatures for the middle three days of the week.

In [20]:
temperatures_w1 

array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

In [21]:
temperatures_w1[0:3]

array([22.5, 25.3, 20.8])

In [27]:
temperatures_w1[5:7]

array([24.8, 21.9])

In [29]:
temperatures_w1[3]

23.4

___________

In [ ]:
5. Create a 2D Array:
Create a 2D NumPy array named temperatures where each row represents temperatures for a different week:
★ Row 1: [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9] (Week 1)
★ Row 2: [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1] (Week 2)

In [31]:
t = np.array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],  [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]])
t

array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
       [19.2, 22.5, 21.3, 24. , 23.5, 22.8, 20.1]])

______________

In [ ]:
6. Inspect and Slice the 2D Array:
● Inspect and print the shape, data type, and total number of elements in the temperatures array.
● Extract the temperatures for each week and the weekends (last two days) for both weeks.

In [32]:
t.shape

(2, 7)

In [33]:
t.dtype

dtype('float64')

In [34]:
t.size

14

In [35]:
t

array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
       [19.2, 22.5, 21.3, 24. , 23.5, 22.8, 20.1]])

In [36]:
t[0]

array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

In [37]:
t[1]

array([19.2, 22.5, 21.3, 24. , 23.5, 22.8, 20.1])

In [38]:
t[0, 5:7]

array([24.8, 21.9])

In [39]:
t[1, 5:7]

array([22.8, 20.1])

_______________

______

### Pandas Series

In [41]:
import pandas as pd

In [ ]:
1. Creating Pandas Series:
● Create a Pandas Series named marks with the following data:
➢ Marks: 95, 92, 89, 85, 80
➢ Custom Indices: 'Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'

In [43]:
marks = pd.Series([95, 92, 89, 85, 80], index = ['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'])
marks

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64

______________

In [ ]:
2. Indexing and Slicing:
● Use the integer index position to access the mark of the 1st rank student.
● Use the loc accessor to retrieve the marks of the top 3 ranks by specifying their index labels.
● Use the iloc accessor to retrieve the mark of the 3rd rank student.
● Apply a boolean mask to filter the Series and retrieve the ranks where the marks are greater than 90.

In [45]:
marks

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64

In [47]:
marks[0]

C:\Users\Surface Pro\AppData\Local\Temp\ipykernel_1380\1318454221.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  marks[0]


95

In [60]:
marks.loc['Rank1':'Rank3']

Rank1    95
Rank2    92
Rank3    89
dtype: int64

In [61]:
marks.iloc[0:3]

Rank1    95
Rank2    92
Rank3    89
dtype: int64

In [62]:
marks > 90

Rank1     True
Rank2     True
Rank3    False
Rank4    False
Rank5    False
dtype: bool

__________

In [ ]:
3. Manipulating Series:
● Modify the mark of the student with the 1st rank to 100.
● Remove the entry corresponding to the last rank from the Series.
● Compute the CGPA by dividing each mark in the Series by 10.

In [64]:
marks['Rank1'] = 100
marks

Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64

In [68]:
marks.drop('Rank5')

Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64

In [69]:
marks.sum()

446

________

## Pandas DataFrame

In [ ]:
1. Creating Pandas DataFrame:
● Create a Pandas DataFrame named transactions with the following data:
➢ TransactionID: 101, 102, 103, 104, 105, 106, 107, 108, 109, 110
➢ ProductCategory: 'Electronics', 'Clothing', 'Electronics', 'Furniture',
'Clothing', 'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'
➢ Region: 'North', 'South', 'North', 'East', 'West', 'North', 'East', 'West',
'South', 'North'
➢ Amount: 200, 150, 300, 450, 200, 250, 300, 180, 350, 400

In [80]:
data = {  'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110], 
        'ProductCategory' : ['Electronics', 'Clothing', 'Electronics', 'Furniture',
'Clothing', 'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'], 
 'Region': ['North', 'South', 'North', 'East', 'West', 'North', 'East', 'West',
'South', 'North'],
        'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400] }

In [86]:
transactions = pd.DataFrame(data )
transactions

TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [88]:
transactions.set_index('TransactionID')

ProductCategory Region  Amount
TransactionID                               
101               Electronics  North     200
102                  Clothing  South     150
103               Electronics  North     300
104                 Furniture   East     450
105                  Clothing   West     200
106               Electronics  North     250
107                 Furniture   East     300
108                  Clothing   West     180
109                 Furniture  South     350
110               Electronics  North     400

__________

In [ ]:
2. Data Exploration:
● Display the transactions DataFrame and its basic information, including head, tail, shape, column names, and data types.
● Display only the 'ProductCategory' and 'Amount' columns.
● Retrieve the last 3 columns of the DataFrame using iloc or loc.
● Filter rows where the 'Region' is 'North' and 'Amount' is greater than 200.
● Find the value counts for the 'ProductCategory' column.
● Find the unique values in the 'Region' column.
● Group by 'Region' and find the mean amount for each region.

In [87]:
transactions.head()

TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200

In [89]:
transactions.tail()

TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [91]:
transactions.shape

(10, 4)

In [93]:
transactions.columns

Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='object')

In [94]:
transactions.dtypes

TransactionID       int64
ProductCategory    object
Region             object
Amount              int64
dtype: object

__________________

In [105]:
transactions[['ProductCategory', 'Amount']]

ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400

In [106]:
transactions

TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [114]:
transactions.iloc[1:4]

TransactionID ProductCategory Region  Amount
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450

In [115]:
transactions.loc[:, ['ProductCategory', 'Region', 'Amount']]

ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400

In [116]:
transactions.iloc[:, -3:]

ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400

In [122]:
transactions[(transactions['Region'] == 'North') & (transactions['Amount'] > 200)]

TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400

### ● Find the value counts for the 'ProductCategory' column.

In [124]:
transactions['ProductCategory'].value_counts()

ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64

### ● Find the unique values in the 'Region' column.

In [157]:
transactions['Region'].unique

<bound method Series.unique of 0    North
1    South
2    North
3     East
4     West
5    North
6     East
7     West
8    South
9    North
Name: Region, dtype: object>

### ● Group by 'Region' and find the mean amount for each region.

In [156]:
transactions.groupby(['Region']).mean(numeric_only = True)

TransactionID  Amount
Region                       
East            105.5   375.0
North           105.0   287.5
South           105.5   250.0
West            106.5   190.0

______

In [ ]:
3. Manipulating the DataFrame:
● Modify the 'Amount' for the transaction with TransactionID 102 to 165.
● Add a new column 'Discount' by calculating 10% of the 'Amount'.
● Remove the row with TransactionID 109.
● Delete the 'Discount' column from the DataFrame.

In [158]:
transactions

TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [ ]:
● Modify the 'Amount' for the transaction with TransactionID 102 to 165.

In [161]:
transactions.loc[102, 'Amount'] = 165
transactions

TransactionID ProductCategory Region  Amount
0            101.0     Electronics  North   200.0
1            102.0        Clothing  South   150.0
2            103.0     Electronics  North   300.0
3            104.0       Furniture   East   450.0
4            105.0        Clothing   West   200.0
5            106.0     Electronics  North   250.0
6            107.0       Furniture   East   300.0
7            108.0        Clothing   West   180.0
8            109.0       Furniture  South   350.0
9            110.0     Electronics  North   400.0
102            NaN             NaN    NaN   165.0

___________

In [ ]:
● Add a new column 'Discount' by calculating 10% of the 'Amount'.

In [165]:
transactions['Discount'] = 0.1 * transactions['Amount']
transactions

TransactionID ProductCategory Region  Amount  Discount
0            101.0     Electronics  North   200.0      20.0
1            102.0        Clothing  South   150.0      15.0
2            103.0     Electronics  North   300.0      30.0
3            104.0       Furniture   East   450.0      45.0
4            105.0        Clothing   West   200.0      20.0
5            106.0     Electronics  North   250.0      25.0
6            107.0       Furniture   East   300.0      30.0
7            108.0        Clothing   West   180.0      18.0
8            109.0       Furniture  South   350.0      35.0
9            110.0     Electronics  North   400.0      40.0
102            NaN             NaN    NaN   165.0      16.5

_________

In [ ]:
● Remove the row with TransactionID 109.

In [178]:
transactions.drop(8, axis =0)

TransactionID ProductCategory Region  Amount  Discount
0            101.0     Electronics  North   200.0      20.0
1            102.0        Clothing  South   150.0      15.0
2            103.0     Electronics  North   300.0      30.0
3            104.0       Furniture   East   450.0      45.0
4            105.0        Clothing   West   200.0      20.0
5            106.0     Electronics  North   250.0      25.0
6            107.0       Furniture   East   300.0      30.0
7            108.0        Clothing   West   180.0      18.0
9            110.0     Electronics  North   400.0      40.0
102            NaN             NaN    NaN   165.0      16.5

__________

In [ ]:
● Delete the 'Discount' column from the DataFrame.

In [180]:
transactions.drop('Discount', axis=1)

TransactionID ProductCategory Region  Amount
0            101.0     Electronics  North   200.0
1            102.0        Clothing  South   150.0
2            103.0     Electronics  North   300.0
3            104.0       Furniture   East   450.0
4            105.0        Clothing   West   200.0
5            106.0     Electronics  North   250.0
6            107.0       Furniture   East   300.0
7            108.0        Clothing   West   180.0
8            109.0       Furniture  South   350.0
9            110.0     Electronics  North   400.0
102            NaN             NaN    NaN   165.0

___________