### 🍁 NUMPY - NUMERICAL PHYTHON

- NumPy (short for Numerical Python) is a library used for working with arrays, performing mathematical operations, and handling large datasets efficiently.

- It’s the foundation for many scientific computing libraries like Pandas, SciPy, and even machine learning frameworks like TensorFlow.

#### 🧠 Why Use NumPy?


- Speed: Much faster than native Python lists for numerical tasks
- Memory efficiency: Uses less memory and supports large datasets
- Convenience: Tons of built-in functions for complex operations


#### 🔧 Key Features


- N-dimensional arrays (ndarray)
- Fast mathematical operations (vectorized computations)
- Linear algebra, Fourier transforms, and random number generation
- Broadcasting (automatic shape adjustment for operations)
- Integration with C/C++ and Fortran code


_________________

#### 📦 Common Functions 

_________
| Function | Description | 
|----------|--------|
| np.array() | Create an array | 
| np.zeros() | Create an array of zeros | 
| np.ones() | Create an array of ones | 
| np.arange() | Create a range of numbers | 
| np.reshape() | Change the shape of an array | 
| np.mean() | Calculate the mean | 
| np.dot() | Matrix multiplication | 
| np.linalg.inv() | Inverse of a matrix | 
___________





### 🍂 ARRAYS

- Arrays are the backbone of numerical computing in Python, especially when using libraries like NumPy. 


#### 🧠 What Is an Array?

- An array is a data structure that stores elements of the same type in a grid-like format.


 In NumPy, arrays are called ndarray (n-dimensional array), and they can be:
- 1D: Like a list → [1, 2, 3]
- 2D: Like a matrix → [[1, 2], [3, 4]]
- 3D and beyond: For tensors, images, or complex datasets


__________

In [2]:
import numpy as np


#### 🔰 Converting list to Numpy Array

#### 💠 METHOD 1

In [20]:
numbers =[10,20,30,40,50,60,70,80,90]
type(numbers)

list

In [21]:
arr = np.array(numbers)
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [8]:
type(arr)

numpy.ndarray

#### 💠 METHOD 2

In [10]:
arr1 = np.array([11, 12, 13, 14, 15])
arr1

array([11, 12, 13, 14, 15])

In [11]:
type(arr1)

numpy.ndarray

### .ndim USED TO ANALYSE DIMENSION OF ARRAY

In [17]:
arr.ndim

1

#### .shape TO UNDERSTAND THE SHAPE OF ARRAY

In [23]:
arr.shape

(9,)

#### .size O UNDERSTAND TOTAL NUMBER OF ELEMENTS

In [24]:
arr.size

9

__________________

### 📊 NumPy Array Features Table


| Feature | Description | Example / Notes | 
|-----|-----|-----|
| ndarray Object | Core data structure for storing elements in N dimensions | np.array([1, 2, 3]) | 
| Homogeneous Data | All elements in a NumPy array must be of the same data type | Faster and more memory-efficient | 
| Shape (.shape) | Tuple indicating dimensions of the array | (3,), (2, 3) | 
| Size (.size) | Total number of elements | array.size | 
| Data Type (.dtype) | Type of elements stored (e.g., int32, float64) | array.dtype | 
| Item Size (.itemsize) | Size in bytes of each element | Useful for memory profiling | 
| Dimensionality (.ndim) | Number of dimensions | 1D, 2D, 3D, etc. | 
| Indexing & Slicing | Access elements using indices and slices | array[0:2], array[:, 1] | 
| Broadcasting | Automatic expansion of arrays for arithmetic operations | array + scalar | 
| Vectorized Operations | Element-wise operations without explicit loops | array * 2, np.sqrt(array) | 
| Reshaping (.reshape) | Change the shape of an array without changing data | array.reshape(2, 3) | 
| Copy vs View | copy() creates a new array; slicing creates a view | array.copy() vs array[::2] | 
| Boolean Indexing | Filter elements based on condition | array[array > 5] | 
| Fancy Indexing | Use arrays of indices to access elements | array[[0, 2]] | 
| Aggregation Functions | Built-in functions like sum, mean, std, min, max | np.mean(array) | 
| Memory Efficiency | Arrays are stored in contiguous blocks of memory | Faster access and computation | 






_______________

### 🔰 CREATING 2-D ARRAY

In [25]:
numbers = [[5,10,15,20], [25,30,35,40]]

In [29]:
num = np.array(numbers)
num

array([[ 5, 10, 15, 20],
       [25, 30, 35, 40]])

In [30]:
type(num)

numpy.ndarray

In [32]:
num.ndim

2

In [33]:
num.shape

(2, 4)

In [34]:
num.size

8

_____________________

### 🔰 CREATING 3-D ARRAY

In [37]:
arr = np.array([
    [[1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 10, 11, 12]],
    
    [[13, 14, 15, 16],
     [17, 18, 19, 20],
     [21, 22, 23, 24]]
])


In [38]:
type(arr)

numpy.ndarray

In [39]:
arr.ndim

3

In [40]:
arr.shape

(2, 3, 4)

In [41]:
arr.size

24

_________________

### CREATING ARRAY WITH:

### ⚜️ 1. np.arange METHOD

-  np.arange—the trusty workhorse of NumPy for generating sequences of numbers with precision and control 🔧.

- If you need precise control over the number of points, use np.linspace.



### 📏 What Is np.arange?

- np.arange(start, stop, step) creates an array of evenly spaced values from start up to (but not including) stop, incremented by step.


In [42]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
np.arange(100, 110)

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [52]:
np.arange(5,50,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

#### 🎯 Use Cases

- Loop indices
- Time steps in simulations
- Grid generation
- Sampling ranges


_________

## ⚜️ np.linspace METHOD

- linspace—a NumPy function that’s all about creating evenly spaced numbers over a specified interval.
- It's like drawing a perfect gradient between two points 🌈.









### 📐 What Is linspace?

numpy.linspace(start, stop, num) generates num evenly spaced values from start to stop, inclusive.


In [46]:
np.linspace(1, 10, 3)

array([ 1. ,  5.5, 10. ])

In [47]:
np.linspace(10,100,10)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [51]:
np.linspace(1,10,2)

array([ 1., 10.])

### 🎯 Use Cases


- Plotting smooth curves
- Creating time intervals
- Sampling functions
- Interpolation

____________

## ⚜️  .reshape()


### 🔧 What .reshape() Does














- It changes the shape of an array to a new configuration, as long as the total number of elements stays the same.
-  .reshape—the shape-shifter of NumPy arrays 🧙‍♂️.
-  It lets you transform the dimensions of an array without changing its data.


In [65]:
arr = np.array([1, 2, 3, 4, 5, 6])

reshaped = arr.reshape(2, 3)  # 2 rows, 3 columns
print(reshaped)

[[1 2 3]
 [4 5 6]]


In [69]:
arr = np.array([10,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30])

r = arr.reshape(4,5) #(hint;use multiples)
r

array([[10, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [73]:
rs = arr.reshape(2,10)

rs

array([[10, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

### 🔄 Common Use Cases
______________________________________
| Use Case | Example | 
|--------|--------|
| Flattening an array | arr.reshape(-1) | 
| Converting 1D to 2D | arr.reshape(1, -1) or arr.reshape(-1, 1) | 
| Preparing image data | arr.reshape(height, width, channels) | 
| Reshaping for ML | arr.reshape(samples, features) | 
__________________________

________________


## ⚜️ np.zeros

- np.zeros is one of NumPy’s simplest yet most useful functions—it creates an array filled entirely with zeros.
-  Perfect for initializing arrays when you know the shape but not the values yet.

### 🔧 Syntax


### 🔰                                   np.zeros(shape, dtype=float)


- shape : Tuple indicating the dimensions of the array
- dtype : Optional; specifies the data type (default is float)

### 1. 🔰 1D Array of Zeros

In [74]:
arr = np.zeros(5)

print(arr)

[0. 0. 0. 0. 0.]


### 🔰 2. 2D Array (Matrix) of Zeros

In [79]:
matrix = np.zeros((3, 4))

print(matrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### 🔰 3. 3D Array of Zeros

In [86]:
cube = np.zeros((2, 3, 4))

cube

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

### 🔰 4. Integer Zeros

In [85]:
int_arr = np.zeros((2, 2), dtype=int)

int_arr

array([[0, 0],
       [0, 0]])

_____________


### 🎯 Use Cases

- Initializing weights in machine learning
- Creating placeholder arrays for computations
- Setting up grids or matrices for simulations
- Preallocating memory for performance

__________________

_________________

## ⚜️ np.ones

- np.ones is NumPy’s way of saying, “Let there be light!”—or at least, let there be a bunch of 1s 🔢.
- It creates an array filled entirely with ones, which is super handy when you need a default value or a starting point for calculations.

### 🧰 Syntax

In [ ]:
np.ones(shape, dtype=None)

- shape: Tuple that defines the dimensions of the array
- dtype: Optional; specifies the data type (default is float)

### 🔰 1. 1D Array of Ones

In [92]:
arr = np.ones(5)

print(arr)

[1. 1. 1. 1. 1.]


### 🔰 2. 2D Matrix of Ones

In [96]:
matrix = np.ones((3, 4))
matrix

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### 🔰 3. Integer Ones

In [95]:
int_matrix = np.ones((2, 2), dtype=int)
int_matrix

array([[1, 1],
       [1, 1]])

### 🔰 4.  3D Array of Ones

In [94]:
cube = np.ones((2, 3, 4))
cube

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

______________________

#### 🎯 Use Cases


- Initializing weights or biases in neural networks
- Creating masks or identity-like matrices
- Placeholder arrays for testing or debugging
- Simulating binary states (e.g., “on” or “active”)

_______________________________

___________

### ✨ Array Creation Functions

_____________________
| Function | Description | Example | 
|-------------|----------|--------|
| np.array() | Create an array from a list or tuple | np.array([1, 2, 3]) | 
| np.zeros() | Create an array filled with zeros | np.zeros((2, 3)) | 
| np.ones() | Create an array filled with ones | np.ones((3, 3)) | 
| np.eye() | Create an identity matrix | np.eye(3) | 
| np.arange() | Create evenly spaced values within a range | np.arange(0, 10, 2) | 
| np.linspace() | Create evenly spaced values over an interval | np.linspace(0, 1, 5) | 
| np.full() | Create an array filled with a specific value | np.full((2, 2), 7) | 
________________





### 🧮 Mathematical Functions

_______________
| Function | Description | Example | 
|--------|-----------|---------|
| np.sum() | Sum of array elements | np.sum(arr) | 
| np.mean() | Mean of array elements | np.mean(arr) | 
| np.std() | Standard deviation | np.std(arr) | 
| np.min() / np.max() | Minimum / Maximum value | np.min(arr) | 
| np.prod() | Product of all elements | np.prod(arr) | 
| np.cumsum() | Cumulative sum | np.cumsum(arr) | 
| np.exp() | Exponential of elements | np.exp(arr) | 
| np.log() | Natural logarithm | np.log(arr) | 
| np.sqrt() | Square root | np.sqrt(arr) | 
| np.abs() | Absolute value | np.abs(arr) | 
___________________





### 🔄 Array Manipulation Functions

________________
| Function | Description | Example | 
|---------|------------|---------|
| np.reshape() | Change shape of array | arr.reshape(2, 3) | 
| np.transpose() | Transpose matrix | arr.T | 
| np.concatenate() | Join arrays | np.concatenate([a, b]) | 
| np.vstack() / np.hstack() | Stack vertically / horizontally | np.vstack([a, b]) | 
| np.split() | Split array into multiple sub-arrays | np.split(arr, 2) | 
| np.flatten() | Flatten multi-dimensional array | arr.flatten() | 
______________________





### 🔄 Array Operations


- Arithmetic: a + b, a * 2, np.sqrt(a)
- Reshape: a.reshape(2, 3)
- Indexing: a[0], a[:, 1]
- Slicing: a[1:4]
- Aggregation: np.mean(a), np.sum(a)




________________________

_______________

### 🔢 Indexing: Accessing Specific Elements

- You use square brackets [] to access elements by their position.

### 🔰 1D Array

In [104]:
arr = np.array([10, 20, 30, 40])

print(arr[2])

30


### 🔰 2D Array

In [111]:
matrix = np.array([[1, 2], [3, 4]])

print(matrix[1, 0])
matrix[0]

3


array([1, 2])

### 🔰 3D Array

In [102]:
cube = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(cube[1, 0, 1])

6


### 🔰 Reverse Indexing

In [108]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[-1]) 
print(arr[-3])

50
30


__________________

________________

### ✂️ Slicing: Grabbing Subsets

- Slicing uses the format [start:stop:step] to extract parts of an array.

### 🔰 1D Slice

In [105]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[1:4])  

[20 30 40]


### 🔰 2D Slice

In [109]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(matrix[0:2, 1:])
matrix[1]

[[2 3]
 [5 6]]


array([4, 5, 6])

### 🔰 Step and Reverse

In [107]:
print(arr[::2])   # Every second element → [10 30 50]
print(arr[::-1])  # Reverse the array → [50 40 30 20 10]

[10 30 50]
[50 40 30 20 10]


In [134]:
arr = np.array([[10, 12, 13, 14, 15], #0 - 0-4
       [16, 17, 18, 19, 20],          #1 - 0-4
       [21, 22, 23, 24, 25],          #2 - 0-4
       [26, 27, 28, 29, 30]])         #3 - 0-4

In [128]:
arr[0][3]

14

In [129]:
arr[1:3]         # 1-2 columns, slicing columns

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [130]:
arr[1:3,1:4]     # 1-2 rows, 1-3 values (rows and column slicing)

array([[17, 18, 19],
       [22, 23, 24]])

In [137]:
arr[2:5, 0:2]

array([[21, 22],
       [26, 27]])

In [132]:
arr = np.array([
    [ 0,  1,  2,  3,  4],
    [ 5,  6,  7,  8,  9],
    [10, 11, 12, 13, 14],
    [15, 16, 17, 18, 19]
])

In [131]:
# Slice
result = arr[1:3, 1:4]

print(result)

[[17 18 19]
 [22 23 24]]


### 🎯 Advanced Indexing

- Boolean indexing: arr[arr > 25]
- Fancy indexing: arr[[0, 2, 4]]

____________

_____________

## ⚜️ np.concatenate()

In [138]:
a = np.array([10,20,30,40])

In [139]:
b = np.array(['abc', 'def', 'ghi', 'jkl'])

In [140]:
np.concatenate([a,b])

array(['10', '20', '30', '40', 'abc', 'def', 'ghi', 'jkl'], dtype='<U11')

______________________________

### ⚜️ COPY v/s VIEW

- A copy creates a new array with its own data.
- It’s independent of the original, so changes to one don’t affect the other.


##### EXERCISE 1

In [144]:
a = np.array([10, 20, 30])

b = a.copy()
b


array([10, 20, 30])

In [148]:
a = np.array([1, 2, 3])

b = a.view()
b[0] = 99
b

array([99,  2,  3])

##### EXERCISE 2

In [151]:
x = np.arange(15,25)
x

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [160]:
y = x.copy()

y

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [161]:
y[::] = 100
y

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [162]:
x.view()

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [163]:
y.view()

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

### 🧬 Copy vs View in NumPy

___________________________________________
| Feature | Copy | View | 
|------|-----|-------|
| Definition | Creates a new array with its own data | Creates a shallow replica that shares data with the original | 
| Memory | Allocates new memory | Shares same memory as original array | 
| Changes | Changes to copy do not affect original | Changes to view do affect original | 
| Use Case | When you want to preserve original data | When you want a temporary slice or reshape | 
___________________



### ☘️ NUMPY SEARCHING ARRAY

- NumPy is like having a supercharged magnifying glass 🔍—you can find values, positions, or patterns with just a few lines of code.

- Here's a breakdown of the most useful tools for searching within arrays:


### ⚜️ 1. np.where() – Find Indices Based on Condition



- Returns the indices of elements that satisfy a condition.

In [165]:
arr = np.arange(10,17)
arr

array([10, 11, 12, 13, 14, 15, 16])

In [166]:
np.where(arr == 12)

(array([2], dtype=int64),)

___________

### ⚜️ 2. Conditional Filtering

In [167]:
numbers = np.array([55,77,55,89,67,55,78,71])
numbers

array([55, 77, 55, 89, 67, 55, 78, 71])

In [168]:
numbers >= 70     # returns true or false

array([False,  True, False,  True, False, False,  True,  True])

In [169]:
numbers[numbers>=70]   # prints values grater than 70

array([77, 89, 78, 71])

_______________

### ⚜️ 3.numpy.extract()

- The numpy.extract() function is a handy way to pull out elements from an array based on a condition.


#### 🧠 Syntax

In [ ]:
numpy.extract(condition, arr)


#### 📌 Parameters

- condition: A boolean array (same shape as arr) that tells which elements to extract.
- arr: The input array from which values are extracted.


In [171]:
arr_new = np.arange(0,21)

arr_new

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

- To Extract Even Numbers

In [174]:
result = np.mod(arr_new, 2) == 0                # mod -> modulus, condition = result
result

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True])

In [175]:
np.extract(result, arr_new)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

______________

### ⚜️ SORTING - np.sort(array_name)

In [178]:
arr1 = np.array([66,56,78,22,31,22,33,34,37])
arr1

array([66, 56, 78, 22, 31, 22, 33, 34, 37])

#### 🔰 SORTING IN ASCENDING ORDER

In [181]:
np.sort(arr1)

array([22, 22, 31, 33, 34, 37, 56, 66, 78])

#### 🔰 SORTING IN DESCENDING ORDER

In [184]:
np.sort(arr1)[::-1]

array([78, 66, 56, 37, 34, 33, 31, 22, 22])

_____________________________________

_______________________